name: Run tests
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck scripts/*.sh
  test:
    needs: [lint]
    strategy:
      matrix:
        buildkit-tag: ["3.2"]
        site-template-ref: ["heads/main"]
        starter-site-ref: ["tags/1.8.0"]
    name: Buildkit ${{ matrix.buildkit-tag }} | Template ${{ matrix.site-template-ref }} | Starter ${{ matrix.starter-site-ref }}
    uses: ./.github/workflows/isle-site-template.yml
    permissions:
      contents: read
    with:
      buildkit-tag: ${{ matrix.buildkit-tag }}
      site-template-ref: ${{ matrix.site-template-ref }}
      starter-site-ref: ${{ matrix.starter-site-ref }}
    secrets: inherit
